// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7_8Nvi1WnwJZokAOmXKeE_k4kUKNEiFM',
    appId: '1:230772297916:android:52b998d9c8d49efe1700b9',
    messagingSenderId: '230772297916',
    projectId: 'bird-partner',
    storageBucket: 'bird-partner.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0Debq9bc4i-jLiW-R2hwRs6FiaYEc1Mo',
    appId: '1:230772297916:ios:979f7849d39c87621700b9',
    messagingSenderId: '230772297916',
    projectId: 'bird-partner',
    storageBucket: 'bird-partner.firebasestorage.app',
    androidClientId: '230772297916-5km5le4aodjpmh81u3qdksa4q4lb3b9e.apps.googleusercontent.com',
    iosClientId: '230772297916-bd92kf9frm7bkmii867aappau4un0h97.apps.googleusercontent.com',
    iosBundleId: 'com.birdpartner.app',
  );

}